import { Brand, Product } from './components/types/productTypes';

export const products: Product[] = [
	{
		id: 1,
		name: 'Adidas Ultraboost X',
		image: 'https://via.placeholder.com/150',
		price: 200,
		brand: Brand.Adidas,
	},
	{
		id: 2,
		name: 'Air Jordan Flightmaster',
		image: 'https://via.placeholder.com/150',
		price: 230,
		brand: Brand.AirJordan,
	},
	{
		id: 3,
		name: 'Converse All-Star Pro',
		image: 'https://via.placeholder.com/150',
		price: 120,
		brand: Brand.Converse,
	},
	{
		id: 4,
		name: 'New Balance Fresh Foam 1080',
		image: 'https://via.placeholder.com/150',
		price: 150,
		brand: Brand.NewBalance,
	},
	{
		id: 5,
		name: 'Nike Air Max 360',
		image: 'https://via.placeholder.com/150',
		price: 220,
		brand: Brand.Nike,
	},
	{
		id: 6,
		name: 'Puma Speedcat OG',
		image: 'https://via.placeholder.com/150',
		price: 110,
		brand: Brand.Puma,
	},
	{
		id: 7,
		name: 'Reebok Zig Dynamica',
		image: 'https://via.placeholder.com/150',
		price: 140,
		brand: Brand.Reebok,
	},
	{
		id: 8,
		name: 'Vans Classic Slip-On',
		image: 'https://via.placeholder.com/150',
		price: 100,
		brand: Brand.Vans,
	},
	{
		id: 9,
		name: 'Adidas SpeedRunner Pro',
		image: 'https://via.placeholder.com/150',
		price: 180,
		brand: Brand.Adidas,
	},
	{
		id: 10,
		name: 'Air Jordan RetroFly',
		image: 'https://via.placeholder.com/150',
		price: 210,
		brand: Brand.AirJordan,
	},
	{
		id: 11,
		name: 'Converse High Street',
		image: 'https://via.placeholder.com/150',
		price: 130,
		brand: Brand.Converse,
	},
	{
		id: 12,
		name: 'New Balance Trailblazer X',
		image: 'https://via.placeholder.com/150',
		price: 160,
		brand: Brand.NewBalance,
	},
	{
		id: 13,
		name: 'Nike VaporMax Plus',
		image: 'https://via.placeholder.com/150',
		price: 240,
		brand: Brand.Nike,
	},
	{
		id: 14,
		name: 'Puma Ignite Flash',
		image: 'https://via.placeholder.com/150',
		price: 190,
		brand: Brand.Puma,
	},
	{
		id: 15,
		name: 'Reebok Flexagon Force',
		image: 'https://via.placeholder.com/150',
		price: 200,
		brand: Brand.Reebok,
	},
	{
		id: 16,
		name: 'Vans Sk8-Hi MTE',
		image: 'https://via.placeholder.com/150',
		price: 140,
		brand: Brand.Vans,
	},
	{
		id: 17,
		name: 'Nike React Infinity',
		image: 'https://via.placeholder.com/150',
		price: 170,
		brand: Brand.Nike,
	},
	{
		id: 18,
		name: 'Adidas NMD_R1 Primeknit',
		image: 'https://via.placeholder.com/150',
		price: 220,
		brand: Brand.Adidas,
	},
	{
		id: 19,
		name: 'Puma Thunder Spectra',
		image: 'https://via.placeholder.com/150',
		price: 120,
		brand: Brand.Puma,
	},
	{
		id: 20,
		name: 'Reebok Aztrek Double Mix',
		image: 'https://via.placeholder.com/150',
		price: 160,
		brand: Brand.Reebok,
	},
	{
		id: 21,
		name: 'Vans UltraRange EXO',
		image: 'https://via.placeholder.com/150',
		price: 150,
		brand: Brand.Vans,
	},
	{
		id: 22,
		name: 'New Balance FuelCell Propel',
		image: 'https://via.placeholder.com/150',
		price: 140,
		brand: Brand.NewBalance,
	},
	{
		id: 23,
		name: 'Nike Blazer Mid 77',
		image: 'https://via.placeholder.com/150',
		price: 130,
		brand: Brand.Nike,
	},
	{
		id: 24,
		name: 'Adidas AlphaBounce Beyond',
		image: 'https://via.placeholder.com/150',
		price: 110,
		brand: Brand.Adidas,
	},
	{
		id: 25,
		name: 'Air Jordan Why Not Zer0',
		image: 'https://via.placeholder.com/150',
		price: 200,
		brand: Brand.AirJordan,
	},
	{
		id: 26,
		name: 'Converse Chuck Taylor All Star Lift',
		image: 'https://via.placeholder.com/150',
		price: 120,
		brand: Brand.Converse,
	},
	{
		id: 27,
		name: 'Nike Kyrie 7',
		image: 'https://via.placeholder.com/150',
		price: 230,
		brand: Brand.Nike,
	},
	{
		id: 28,
		name: 'Adidas Supa Boost 700',
		image: 'https://via.placeholder.com/150',
		price: 250,
		brand: Brand.Adidas,
	},
];
